### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by chrismyers81** [Canyoneer/ValenceRT-DecodingTool#3]
With my USB<>RS485 converter (an R.E. Smith USBA4) when I'd try to run the script on Debian 12, I'd get an error -

```
# python ValRTRX.py /dev/ttyUSB0 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/serial/serialposix.py", line 167, in _set_rs485_mode
    fcntl.ioctl(self.fd, TIOCGRS485, buf)
OSError: [Errno 25] Inappropriate ioctl for device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/scripts/valence/ValRTRX.py", line 41, in <module>
    s.rs485_mode = serial.rs485.RS485Settings(True, False, False, None, None)
    ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/serial/serialutil.py", line 500, in rs485_mode
    self._reconfigure_port()
  File "/usr/local/lib/python3.11/dist-packages/serial/serialposix.py", line 527, in _reconfigure_port
    self._set_rs485_mode(self._rs485_mode)
  File "/usr/local/lib/python3.11/dist-packages/serial/serialposix.py", line 190, in _set_rs485_mode
    raise ValueError('Failed to set RS485 mode: {}'.format(e))
ValueError: Failed to set RS485 mode: [Errno 25] Inappropriate ioctl for device
```

A fix that seems to work is to comment out line 41; after doing so the script seems to run fine --

#s.rs485_mode = serial.rs485.RS485Settings(True, False, False, None, None)

**Comment by Canyoneer** [comment]
Thanks! I never tested it on a Linux system before. I could reproduce it with a CH340 and Debian 12. 

As far as I can tell the RS485Settings don't have any effect anyway for this application.
